=== NingMoe/HelloWorld/MyCProgram/近期工作/路透/mpc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="TaskInfo">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Data">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="userToken"/>
							<xs:element name="EventInfo"/>
							<xs:element name="Mappings">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Mapping" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="H"/>
													<xs:element name="L"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="ProjectPath"/>
							<xs:element name="Logicpath"/>
							<xs:element name="Metadatas">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Metadata" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Key"/>
													<xs:element name="Value"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== NingMoe/HelloWorld/MyCProgram/近期工作/路透/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<TaskInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\Work\HelloWorld.git\trunk\MyCProgram\近期工作\路透\mpc.xsd">
	<Data>
		<userToken/>
		<EventInfo/>
		<Mappings>
			<Mapping>
				<H/>
				<L/>
			</Mapping>
		</Mappings>
		<ProjectPath/>
		<Logicpath/>
		<Metadatas>
			<Metadata>
				<Key/>
				<Value/>
			</Metadata>
		</Metadatas>
	</Data>
</TaskInfo>
